In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
df_00 = pd.read_csv('1.csv')

In [91]:
df_25 = pd.read_csv('2.csv', sep = ';')

In [92]:
df_25

,Unnamed: 0,Car,Price,Date,Km,Transmission,Fuel,PS,Consumption,Location
0,0,BMW X3 30d xDrive SAG,CHF 38'900.–,32.018,122'000 km,Automatikgetriebe,Diesel,265 PS (195 kW),5.8 l/100 km,6467 Schattdorf
1,1,BMW 225xe Active Tourer,CHF 24'920.–,82.020,83'000 km,Automatikgetriebe,Plug-in hybrid Benzin/Elektro,224 PS (165 kW),2.2 l/100 km,6467 Schattdorf
2,2,BMW Z4 sDrive 20i M Sport St.,CHF 64'500.–,Neues Fahrzeug,10 km,Automat,Benzin,197 PS (145 kW),-,4900 Langenthal
3,3,BMW XM Plug-in Hybrid,CHF 144'555.–,52.023,5'000 km,Automatikgetriebe,Plug-in hybrid Benzin/Elektro,653 PS (480 kW),1.6 l/100 km,6467 Schattdorf
4,4,LAND ROVER Discovery Sport 2.0 I4 250cv Dynami...,CHF 77'990.–,Vorführmodell,1'000 km,Automatikgetriebe,Mild-Hybrid Benzin/Elektro,249 PS (183 kW),9.7 l/100 km,2800 Delémont
...,...,...,...,...,...,...,...,...,...,...
49975,49975,VW Golf 1.5 eTSI mHEV ACT R-Line 75 Edition DSG,CHF 42'300.–,Neues Fahrzeug,10 km,Automatikgetriebe,Mild-Hybrid Benzin/Elektro,150 PS (110 kW),-,9444 Diepoldsau
49976,49976,MERCEDES-BENZ A 35 AMG 4matic,CHF 34'600.–,102.019,99'800 km,Halbautomatisches Getriebe,Benzin,306 PS (225 kW),9.3 l/100 km,8500 Frauenfeld
49977,49977,MASERATI Levante S 3.0 V6 GranSport Automatica,CHF 53'900.–,52.017,57'000 km,Automat,Benzin,430 PS (316 kW),10.9 l/100 km,4123 Allschwil
49978,49978,VW T7 Multivan 1.4 eHybrid Liberty DSG,CHF 65'900.–,122.023,3'000 km,Automatikgetriebe,Plug-in hybrid Benzin/Elektro,217 PS (160 kW),-,6283 Baldegg
49979,49979,TOYOTA bZ4X Premium AWD,CHF 62'000.–,Neues Fahrzeug,20 km,Halbautomatisches Getriebe,Elektro,218 PS (160 kW),411 km,4632 Trimbach

In [90]:
def convert_dates(val):
    if val in ['Neues Fahrzeug', 'Vorführmodell']:
        return None  # Exclude these specific strings
    else:
        parts = val.split('.')
        if len(parts) == 2:
            # Assuming the format is like 32.018 => 3.2018
            month = int(parts[0]) % 100  # Get last two digits and use as month
            year = '20' + parts[1]  # Assuming all years are in the 2000s
            return f'{month}.{year}'
        else:
            return None  # Return None for any format that doesn't match

# Apply the custom function to the 'Dates' column
df = df['Date'].apply(convert_dates)

# Display the result
print(df)

0          7.202024
1          7.202024
2          7.202024
3          7.202024
4          7.202024
            ...
157572    11.202009
157573     7.202002
157574     8.202015
157575    10.202006
157576    11.202007
Name: Date, Length: 157574, dtype: object

In [52]:
df_50 = pd.read_csv('3.csv')

In [53]:
df_merged = pd.concat([df_00, df_25, df_50], axis=0)

In [54]:
df_merged.count()

Unnamed: 0       99980
Car             158560
Price           158557
Date            158557
Km              158557
Transmission    158557
Fuel            158557
PS              158557
Consumption     158557
Location        158557
dtype: int64

In [55]:
df_merged.drop('Unnamed: 0',axis = 1, inplace = True)

In [56]:
df_merged.head()

,Car,Price,Date,Km,Transmission,Fuel,PS,Consumption,Location
0,MERCEDES-BENZ GLB 250 4Matic AMG Line 8G-Troni...,CHF 44'450.–,02.2020,45'486 km,Automat,Benzin,224 PS (165 kW),8.9 l/100 km,8408 Winterthur (Wülflingen)
1,AUDI RS e-tron GT quattro,CHF 155'990.–,Neues Fahrzeug,9 km,Automatikgetriebe,Elektro,599 PS (440 kW),469 km,4147 Aesch
2,BMW 120d xDrive Sport Line,CHF 36'900.–,05.2023,28'100 km,Automat,Diesel,190 PS (140 kW),5.2 l/100 km,7000 Chur
3,MERCEDES-BENZ GLK 250 CDI BlueEfficiency 4Mati...,CHF 18'799.–,05.2012,68'200 km,Automat,Diesel,204 PS (150 kW),6.5 l/100 km,8156 Oberhasli
4,SEAT Leon ST 2.0 TSI Cupra 290 DSG,CHF 21'900.–,03.2016,86'000 km,Halbautomatisches Getriebe,Benzin,290 PS (213 kW),6.6 l/100 km,5417 Untersiggenthal

In [57]:
df_merged

,Car,Price,Date,Km,Transmission,Fuel,PS,Consumption,Location
0,MERCEDES-BENZ GLB 250 4Matic AMG Line 8G-Troni...,CHF 44'450.–,02.2020,45'486 km,Automat,Benzin,224 PS (165 kW),8.9 l/100 km,8408 Winterthur (Wülflingen)
1,AUDI RS e-tron GT quattro,CHF 155'990.–,Neues Fahrzeug,9 km,Automatikgetriebe,Elektro,599 PS (440 kW),469 km,4147 Aesch
2,BMW 120d xDrive Sport Line,CHF 36'900.–,05.2023,28'100 km,Automat,Diesel,190 PS (140 kW),5.2 l/100 km,7000 Chur
3,MERCEDES-BENZ GLK 250 CDI BlueEfficiency 4Mati...,CHF 18'799.–,05.2012,68'200 km,Automat,Diesel,204 PS (150 kW),6.5 l/100 km,8156 Oberhasli
4,SEAT Leon ST 2.0 TSI Cupra 290 DSG,CHF 21'900.–,03.2016,86'000 km,Halbautomatisches Getriebe,Benzin,290 PS (213 kW),6.6 l/100 km,5417 Untersiggenthal
...,...,...,...,...,...,...,...,...,...
58575,ALFA ROMEO 147 1.9 16V JTD Q2,CHF 3'890.–,11.2009,226'220 km,Schaltgetriebe manuell,Diesel,150 PS (110 kW),5.9 l/100 km,9113 Degersheim
58576,MERCEDES-BENZ SL 500 Automatic,CHF 17'900.–,07.2002,75'000 km,Automatikgetriebe,Benzin,306 PS (225 kW),12.1 l/100 km,8051 Zürich/ Schwamendingen
58577,SUBARU Forester 2.0D Luxury Lineatronic,CHF 14'500.–,08.2015,106'700 km,Stufenlos,Diesel,147 PS (108 kW),6.1 l/100 km,8253 Diessenhofen
58578,PEUGEOT 407 SW 2.0 HDI SR Selection,CHF 1'700.–,10.2006,152'347 km,Automat,Diesel,136 PS (100 kW),7.2 l/100 km,1713 St. Antoni
58579,BMW 635d Steptronic,CHF 17'500.–,11.2007,88'000 km,Automat,Diesel,286 PS (210 kW),7.2 l/100 km,3754 Diemtigen

In [58]:
df_merged1 = df_merged.reset_index(drop=True)

In [59]:
df = df_merged1

In [33]:
df

,Car,Price,Date,Km,Transmission,Fuel,PS,Consumption,Location
0,MERCEDES-BENZ GLB 250 4Matic AMG Line 8G-Troni...,CHF 44'450.–,02.2020,45'486 km,Automat,Benzin,224 PS (165 kW),8.9 l/100 km,8408 Winterthur (Wülflingen)
1,AUDI RS e-tron GT quattro,CHF 155'990.–,Neues Fahrzeug,9 km,Automatikgetriebe,Elektro,599 PS (440 kW),469 km,4147 Aesch
2,BMW 120d xDrive Sport Line,CHF 36'900.–,05.2023,28'100 km,Automat,Diesel,190 PS (140 kW),5.2 l/100 km,7000 Chur
3,MERCEDES-BENZ GLK 250 CDI BlueEfficiency 4Mati...,CHF 18'799.–,05.2012,68'200 km,Automat,Diesel,204 PS (150 kW),6.5 l/100 km,8156 Oberhasli
4,SEAT Leon ST 2.0 TSI Cupra 290 DSG,CHF 21'900.–,03.2016,86'000 km,Halbautomatisches Getriebe,Benzin,290 PS (213 kW),6.6 l/100 km,5417 Untersiggenthal
...,...,...,...,...,...,...,...,...,...
158575,ALFA ROMEO 147 1.9 16V JTD Q2,CHF 3'890.–,11.2009,226'220 km,Schaltgetriebe manuell,Diesel,150 PS (110 kW),5.9 l/100 km,9113 Degersheim
158576,MERCEDES-BENZ SL 500 Automatic,CHF 17'900.–,07.2002,75'000 km,Automatikgetriebe,Benzin,306 PS (225 kW),12.1 l/100 km,8051 Zürich/ Schwamendingen
158577,SUBARU Forester 2.0D Luxury Lineatronic,CHF 14'500.–,08.2015,106'700 km,Stufenlos,Diesel,147 PS (108 kW),6.1 l/100 km,8253 Diessenhofen
158578,PEUGEOT 407 SW 2.0 HDI SR Selection,CHF 1'700.–,10.2006,152'347 km,Automat,Diesel,136 PS (100 kW),7.2 l/100 km,1713 St. Antoni
158579,BMW 635d Steptronic,CHF 17'500.–,11.2007,88'000 km,Automat,Diesel,286 PS (210 kW),7.2 l/100 km,3754 Diemtigen

In [61]:
# Assuming df is your DataFrame
# Exclude 'Neues Fahrzeug' rows and find duplicates (keeping the first occurrence)
duplicates = df[(df.duplicated(keep='first')) & (df['Date'] != 'Neues Fahrzeug')]

# To track all duplicates including the first occurrence, we can mark all duplicates and then filter
all_duplicates_mask = df.duplicated(keep=False)  # Marks all duplicates
# Exclude 'Neues Fahrzeug' rows from this mask
all_duplicates_mask &= df['Date'] != 'Neues Fahrzeug'
# Extract all duplicates based on the mask
all_duplicates = df[all_duplicates_mask]

# Now, remove duplicates from the original DataFrame while keeping 'Neues Fahrzeug' rows unchanged
df_neues_fahrzeug = df[df['Date'] == 'Neues Fahrzeug']
df_others = df[df['Date'] != 'Neues Fahrzeug'].drop_duplicates()

# Concatenate the non-duplicate and 'Neues Fahrzeug' rows back together
final_df = pd.concat([df_neues_fahrzeug, df_others], ignore_index=True)

# all_duplicates contains all duplicates except those marked as 'Neues Fahrzeug'

In [62]:
all_duplicates

,Car,Price,Date,Km,Transmission,Fuel,PS,Consumption,Location
146,SKODA OCTAVIA 2.0 TSI RS DSG,CHF 39'980.–,05.2023,50 km,Halbautomatisches Getriebe,Benzin,245 PS,7.3 l/100 km,9542 Münchwilen
209,SKODA Octavia Combi 2.0 TDI RS 4x4 DSG,CHF 36'800.–,05.2022,31'200 km,Halbautomatisches Getriebe,Diesel,200 PS (147 kW),6.2 l/100 km,9320 Arbon
549,FIAT TIPO 1.5 Hybrid DCT Station Wagon,CHF 23'889.–,10.2023,20 km,Automatikgetriebe,Voll-Hybrid Benzin/Elektro,130 PS (96 kW),5.4 l/100 km,5610 Wohlen (AG)
824,VW E-UP ***TOP AUSSTATTUNG***,CHF 23'900.–,11.2023,20 km,Automat,Elektro,82 PS (60 kW),225 km,8404 Winterthur
1006,SKODA Enyaq Coupé RS iV 80 4x4,CHF 56'890.–,Vorführmodell,50 km,Automatikgetriebe,Elektro,299 PS (220 kW),521 km,4147 Aesch
...,...,...,...,...,...,...,...,...,...
158260,AUDI A5 Cabriolet 2.0 TFSI quattro S-tronic,CHF 14'499.–,12.2010,124'000 km,Halbautomatisches Getriebe,Benzin,211 PS (155 kW),7.7 l/100 km,3297 Leuzigen
158499,MASERATI Quattroporte 4.2 V8 DuoSelect,CHF 24'500.–,12.2004,77'000 km,Halbautomatisches Getriebe,Benzin,400 PS (295 kW),18.9 l/100 km,8505 Pfyn
158500,MASERATI Quattroporte 4.2 V8 DuoSelect,CHF 24'500.–,12.2004,77'000 km,Halbautomatisches Getriebe,Benzin,400 PS (295 kW),18.9 l/100 km,8505 Pfyn
158539,VW Golf Variant 1.4 TSI Comfortline DSG,CHF 6'900.–,12.2013,204'000 km,Halbautomatisches Getriebe,Benzin,122 PS (90 kW),5.1 l/100 km,1868 Collombey
158540,VW Golf Variant 1.4 TSI Comfortline DSG,CHF 6'900.–,12.2013,204'000 km,Halbautomatisches Getriebe,Benzin,122 PS (90 kW),5.1 l/100 km,1868 Collombey

In [63]:
final_df

,Car,Price,Date,Km,Transmission,Fuel,PS,Consumption,Location
0,AUDI RS e-tron GT quattro,CHF 155'990.–,Neues Fahrzeug,9 km,Automatikgetriebe,Elektro,599 PS (440 kW),469 km,4147 Aesch
1,VW Tiguan 1.4TSIPHEV R-L DSG 245PS 5 Jahre Wer...,CHF 50'900.–,Neues Fahrzeug,10 km,Halbautomatisches Getriebe,Plug-in hybrid Benzin/Elektro,245 PS (180 kW),-,5702 Niederlenz
2,VW Touareg 3.0 TSI e Hybrid Atmosphere 5 Jahre...,CHF 69'900.–,Neues Fahrzeug,50 km,Automat,Plug-in hybrid Benzin/Elektro,381 PS (284 kW),-,5702 Niederlenz
3,AUDI Q5 Sportback 50 TFSI e PHEV S line quattr...,CHF 56'900.–,Neues Fahrzeug,10 km,Halbautomatisches Getriebe,Plug-in hybrid Benzin/Elektro,299 PS (220 kW),-,5702 Niederlenz
4,SKODA Octavia Combi 2.0 TDI DSG Ambition,CHF 39'990.–,Neues Fahrzeug,20 km,Automatikgetriebe,Diesel,150 PS (110 kW),-,1716 Plaffeien
...,...,...,...,...,...,...,...,...,...
157572,ALFA ROMEO 147 1.9 16V JTD Q2,CHF 3'890.–,11.2009,226'220 km,Schaltgetriebe manuell,Diesel,150 PS (110 kW),5.9 l/100 km,9113 Degersheim
157573,MERCEDES-BENZ SL 500 Automatic,CHF 17'900.–,07.2002,75'000 km,Automatikgetriebe,Benzin,306 PS (225 kW),12.1 l/100 km,8051 Zürich/ Schwamendingen
157574,SUBARU Forester 2.0D Luxury Lineatronic,CHF 14'500.–,08.2015,106'700 km,Stufenlos,Diesel,147 PS (108 kW),6.1 l/100 km,8253 Diessenhofen
157575,PEUGEOT 407 SW 2.0 HDI SR Selection,CHF 1'700.–,10.2006,152'347 km,Automat,Diesel,136 PS (100 kW),7.2 l/100 km,1713 St. Antoni
157576,BMW 635d Steptronic,CHF 17'500.–,11.2007,88'000 km,Automat,Diesel,286 PS (210 kW),7.2 l/100 km,3754 Diemtigen

In [65]:
df = final_df

In [66]:
df['Price'] = df['Price'].str.replace('CHF ', '', regex=False).str.replace("'", '', regex=False).str.rstrip('.–')

In [68]:
df['Km'] = df['Km'].str.replace("'", "").str.replace(" km", "", regex=False)

In [80]:
non_numeric_km = df[~df['Km'].str.contains('^[0-9]+$', na=False)]

In [81]:
non_numeric_km

Empty DataFrame
Columns: [Car, Price, Date, Km, Transmission, Fuel, PS, Consumption, Location]
Index: []

In [75]:
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [Car, Price, Date, Km, Transmission, Fuel, PS, Consumption, Location]
Index: []

In [74]:
df = df.dropna()

In [79]:
df['Km'] = df['Km'].str.replace("-", "0").str.replace(" km", "", regex=False)

C:\Users\matteo.protopapa\AppData\Local\Temp\ipykernel_30364\666281210.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Km'] = df['Km'].str.replace("", "0").str.replace(" km", "", regex=False)

In [82]:
df[['PS', 'kW']] = df['PS'].str.extract(r'(\d+) PS \((\d+) kW\)')

C:\Users\matteo.protopapa\AppData\Local\Temp\ipykernel_30364\2913249112.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['PS', 'kW']] = df['PS'].str.extract(r'(\d+) PS \((\d+) kW\)')
C:\Users\matteo.protopapa\AppData\Local\Temp\ipykernel_30364\2913249112.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['PS', 'kW']] = df['PS'].str.extract(r'(\d+) PS \((\d+) kW\)')

In [84]:
df['Date'] = df['Date'].str.replace('Neues Fahrzeug', '07.2024', regex=False) # auf 07.2024 erhöhen
df['Date'] = df['Date'].str.replace('Vorführmodell', '07.2023', regex=False)

# Alle Werte mit Format YYYY mit 01. ergänzen
df['Date'] = df['Date'].apply(lambda x: '01.' + x if len(x) == 4 and x.isdigit() else x)

# df['Date'] in Datentypen 'datetime' umwandeln
df['Date'] = pd.to_datetime(df['Date'], format='%m.%Y')

C:\Users\matteo.protopapa\AppData\Local\Temp\ipykernel_30364\2819651266.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = df['Date'].str.replace('Neues Fahrzeug', '07.2024', regex=False) # auf 07.2024 erhöhen
C:\Users\matteo.protopapa\AppData\Local\Temp\ipykernel_30364\2819651266.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = df['Date'].str.replace('Vorführmodell', '07.2023', regex=False)
C:\Users\matteo.protopapa\AppData\Local\Temp\ipykernel_30364\2819651266.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = df['Date'].apply(lambda x: '01.' + x if len(x) == 4 and x.isdigit() else x)

ValueError: time data '32.018' does not match format '%m.%Y' (match)

In [85]:
df[df['Date'] == '32.018']

,Car,Price,Date,Km,Transmission,Fuel,PS,Consumption,Location,kW
63110,BMW X3 30d xDrive SAG,38900,32.018,0102020000000,Automatikgetriebe,Diesel,265,5.8 l/100 km,6467 Schattdorf,195
63151,MERCEDES-BENZ G 350 d 7G-Tronic,79895,32.018,06040100000,Automat,Diesel,245,9.9 l/100 km,8408 Winterthur-Wülflingen,180
63941,BMW X3 xDrive M40i Steptronic,35990,32.018,0102060300000,Automat,Benzin,360,8.4 l/100 km,1933 Sembrancher,265
63992,PORSCHE Macan GTS PDK APPLE CAR PLAY,48500,32.018,09010805000,Halbautomatisches Getriebe,Benzin,360,9.2 l/100 km,1228 Plan-les-Ouates,265
64084,MERCEDES-BENZ C 250 d Swiss Star AMG Line 4Mat...,28800,32.018,07030103000,Automat,Diesel,204,5.1 l/100 km,1950 Sion,150
...,...,...,...,...,...,...,...,...,...,...
104750,BMW 435d Gran Coupé xDrive M Sport Steptronic,31990,32.018,0102070000000,Automat,Diesel,313,5.7 l/100 km,8370 Sirnach,230
104755,BMW 218d xDrive Gran Tourer Steptronic,15600,32.018,0104060000000,Automat,Diesel,150,4.7 l/100 km,3629 Oppligen,110
105200,HONDA Civic 2.0 i-VTEC Type R GT,32500,32.018,06040705000,Schaltgetriebe manuell,Benzin,320,7.7 l/100 km,1860 Aigle,235
105201,DACIA Duster TCe 125 Prestige 4x4,16800,32.018,07050000000,Schaltgetriebe manuell,Benzin,125,6.4 l/100 km,1860 Aigle,92
105296,AUDI S5 Cabriolet 3.0 V6 TFSI quattro T-Tronic,49800,32.018,03020800000,Automatikgetriebe,Benzin,353,7.9 l/100 km,8500 Frauenfeld,260

In [86]:
df.iloc[63150:63153]

,Car,Price,Date,Km,Transmission,Fuel,PS,Consumption,Location,kW
63150,DS AUTOMOBILES DS3 1.6 THP Racing,5880,82.012,0106070000000,Schaltgetriebe manuell,Benzin,207,6.4 l/100 km,5723 Teufenthal AG,152
63151,MERCEDES-BENZ G 350 d 7G-Tronic,79895,32.018,06040100000,Automat,Diesel,245,9.9 l/100 km,8408 Winterthur-Wülflingen,180
63152,AUDI Q3 Sportback 40 TDI S line quattro,42895,32.021,03080800000,Halbautomatisches Getriebe,Diesel,200,-,8408 Winterthur-Wülflingen,147

In [87]:
df_25

,Unnamed: 0,Car,Price,Date,Km,Transmission,Fuel,PS,Consumption,Location
0,0,BMW X3 30d xDrive SAG,CHF 38'900.–,32.018,122'000 km,Automatikgetriebe,Diesel,265 PS (195 kW),5.8 l/100 km,6467 Schattdorf
1,1,BMW 225xe Active Tourer,CHF 24'920.–,82.020,83'000 km,Automatikgetriebe,Plug-in hybrid Benzin/Elektro,224 PS (165 kW),2.2 l/100 km,6467 Schattdorf
2,2,BMW Z4 sDrive 20i M Sport St.,CHF 64'500.–,Neues Fahrzeug,10 km,Automat,Benzin,197 PS (145 kW),-,4900 Langenthal
3,3,BMW XM Plug-in Hybrid,CHF 144'555.–,52.023,5'000 km,Automatikgetriebe,Plug-in hybrid Benzin/Elektro,653 PS (480 kW),1.6 l/100 km,6467 Schattdorf
4,4,LAND ROVER Discovery Sport 2.0 I4 250cv Dynami...,CHF 77'990.–,Vorführmodell,1'000 km,Automatikgetriebe,Mild-Hybrid Benzin/Elektro,249 PS (183 kW),9.7 l/100 km,2800 Delémont
...,...,...,...,...,...,...,...,...,...,...
49975,49975,VW Golf 1.5 eTSI mHEV ACT R-Line 75 Edition DSG,CHF 42'300.–,Neues Fahrzeug,10 km,Automatikgetriebe,Mild-Hybrid Benzin/Elektro,150 PS (110 kW),-,9444 Diepoldsau
49976,49976,MERCEDES-BENZ A 35 AMG 4matic,CHF 34'600.–,102.019,99'800 km,Halbautomatisches Getriebe,Benzin,306 PS (225 kW),9.3 l/100 km,8500 Frauenfeld
49977,49977,MASERATI Levante S 3.0 V6 GranSport Automatica,CHF 53'900.–,52.017,57'000 km,Automat,Benzin,430 PS (316 kW),10.9 l/100 km,4123 Allschwil
49978,49978,VW T7 Multivan 1.4 eHybrid Liberty DSG,CHF 65'900.–,122.023,3'000 km,Automatikgetriebe,Plug-in hybrid Benzin/Elektro,217 PS (160 kW),-,6283 Baldegg
49979,49979,TOYOTA bZ4X Premium AWD,CHF 62'000.–,Neues Fahrzeug,20 km,Halbautomatisches Getriebe,Elektro,218 PS (160 kW),411 km,4632 Trimbach

In [83]:
df.head(1)

,Car,Price,Date,Km,Transmission,Fuel,PS,Consumption,Location,kW
0,AUDI RS e-tron GT quattro,155990,Neues Fahrzeug,090,Automatikgetriebe,Elektro,599,469 km,4147 Aesch,440